// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

const (
	Errors_USER_NOT_FOUND  = "ErrorReason_USER_NOT_FOUND"
	Errors_CONTENT_MISSING = "ErrorReason_CONTENT_MISSING"
)

func IsUSER_NOT_FOUND(err error) bool {
	return errors.Reason(err) == Errors_USER_NOT_FOUND
}

func IsCONTENT_MISSING(err error) bool {
	return errors.Reason(err) == Errors_CONTENT_MISSING
}
